### ISSUE TITLE
Curioso: Usou gerador de classes? Ou implementou manualmente?

### ISSUE THREAD

**Issue by rafaelpatro** [jansenfelipe/nfephp-serialize#2]
Olá @jansenfelipe 
Seu projeto é bem interessante, e bem construído. Agradeço por compartilhá-lho.

Fiquei curioso em saber como você implementou todas aquelas classes em _src/NotaFiscal/_. É um bocado de trabalho.
Você usou algum software para gerar as classes, com base nos XSDs? Qual software usou? Ou fez uma por uma manualmente?

Obrigado novamente, e boa semana.

**Comment by jansenfelipe** [comment]
@rafaelpatro gerei com base nos XSDs. Utilizei este https://github.com/goetas/xsd2php

**Comment by rafaelpatro** [comment]
Legal. Estou planejando implementar os serviços de manipulação das Notas Fiscais (enviar, receber, cancelar, etc).
Mas devido as atualizações recorrentes da Receita Federal, procuro uma solução que leia os webservices, e monte as classes necessárias em tempo de execução. E essa biblioteca xsd2php já faz boa parte do trabalho. Obrigado, e bom domingo.
