### ISSUE TITLE
Importando no Laravel

### ISSUE THREAD

**Issue by fabiogalera** [jansenfelipe/nfephp-serialize#3]
Olá,

Estou tentando importar sua classe no Laravel 5.2. Instalei pelo composer e adicionei a linha no app.php, dentro dos providers:

```
    'JansenFelipe\NFePHPSerialize\NFePHPSerialize',
```

Porém quando eu compilo, o optimizer da um erro:

  Call to undefined method JansenFelipe\NFePHPSerialize\NFePHPSerialize::isDeferred()

**Comment by jansenfelipe** [comment]
@fabiogalera boa tarde!

Você não precisa adicionar nada no app.php do Laravel para o package funcionar.

Basta chamar o comando `composer require jansenfelipe/nfephp-serialize`
